# Generated by Django 4.0.2 on 2022-03-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_facebook',
            field=models.BooleanField(default=False, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_instagram',
            field=models.BooleanField(default=False, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_twitter',
            field=models.BooleanField(default=False, verbose_name='Twitter'),
        ),
    ]
