# Generated by Django 4.0.2 on 2022-03-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_is_facebook_post_is_instagram_post_is_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contactno',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
