# Generated by Django 4.0.2 on 2022-03-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_user_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='16692.jpg', upload_to='blog_images'),
        ),
    ]
