# Generated by Django 4.0.3 on 2022-03-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_facebook',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_instagram',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_twitter',
        ),
        migrations.AddField(
            model_name='post',
            name='social_media',
            field=models.CharField(choices=[('Twitter', 'twitter'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
