# Generated by Django 4.0.3 on 2022-03-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_remove_post_is_facebook_remove_post_is_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='social_media',
        ),
        migrations.AddField(
            model_name='post',
            name='is_facebook',
            field=models.BooleanField(default=False, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_instagram',
            field=models.BooleanField(default=False, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_twitter',
            field=models.BooleanField(default=False, verbose_name='Twitter'),
        ),
    ]
