# Generated by Django 4.0.2 on 2022-03-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_remove_post_social_media_post_is_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contactno',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
