# Generated by Django 4.0.2 on 2022-03-21 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_user_contactno'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
                ('api_key_secret', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('access_token_secret', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
