# Generated by Django 4.0.2 on 2022-03-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_twittercredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twitter_access_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_access_token_secret',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_api_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_api_key_secret',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='TwitterCredentials',
        ),
    ]
