# Generated by Django 4.0.2 on 2022-03-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='blog_images'),
            preserve_default=False,
        ),
    ]
