# Generated by Django 4.0.2 on 2022-03-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_user_insta_password_user_insta_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_access_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
